<?php
/**
 * Core logic for generating the standalone recovery bunker.
 */
/**
 * Helper to extract raw PHP code from a file, removing tags and sanitizing whitespace.
 */
function sc_clean_logic($path) {
    if (!file_exists($path)) return "// Logic file missing: $path";
    $content = file_get_contents($path);
    // 1. Remove opening tag and any immediate whitespace/newlines
    $content = preg_replace('/^<\?php\s*/i', '', $content);
    // 2. Remove closing tag and any trailing whitespace
    $content = preg_replace('/\s*\?>\s*$/', '', $content);
    return trim($content);
}

function sc_generate_bunker() {
    $relApp = str_replace(CJOS_PATH_ROOT . '/', '', CJOS_PATH_APP);
    
    $createLogic = sc_clean_logic(CJOS_PATH_APP . '/api/sc_logic_create.php');
    $restoreLogic = sc_clean_logic(CJOS_PATH_APP . '/api/sc_logic_restore.php');

    $code = "<?php\n" .
    "// ==============================================================================\n" .
    "// 🛑 AI WARNING: DO NOT EDIT THIS FILE DIRECTLY! 🛑\n" .
    "// This 'recovery.php' file is AUTO-GENERATED by 'app/api/sc_logic_bunker.php'.\n" .
    "// If you need to modify the backup or restore logic, you MUST patch the following:\n" .
    "// 1. app/api/sc_logic_bunker.php (For UI and Bunker-specific logic)\n" .
    "// 2. app/api/sc_logic_create.php (For backup creation logic)\n" .
    "// 3. app/api/sc_logic_restore.php (For backup restoration logic)\n" .
    "// ANY DIRECT MODIFICATIONS TO THIS FILE WILL BE OVERWRITTEN AND LOST.\n" .
    "// ==============================================================================\n\n" .
    "    // --- ISOLATED EMERGENCY RECOVERY BUNKER ---\n" .
    "    require_once __DIR__ . '/$relApp/paths.php';\n" .
    $createLogic . "\n" .
    $restoreLogic . "\n" .
    <<<'PHP'
    $authFile = CJOS_PATH_DATA . "/authentication-private.json";
    $backupDir = CJOS_PATH_APP . "/backups/checkpoints";
    $metaFile = $backupDir . "/meta.json";
    $protectedAppsList = sc_get_protected_apps();
    
    function is_authed() {
        if (!file_exists($GLOBALS["authFile"])) return true;
        $config = json_decode(file_get_contents($GLOBALS["authFile"]), true);
        if (($config["attempts"] ?? 0) >= 3) return false;
        if (!isset($_COOKIE["cjos_auth_token"])) return false;
        $parts = explode(".", $_COOKIE["cjos_auth_token"]);
        if (count($parts) !== 2) return false;
        return ($parts[1] === md5($parts[0] . $config["hash"] . $config["created_at"]));
    }

    $msg = isset($_GET["msg"]) ? $_GET["msg"] : ""; 
    $clientState = null; 
    $success = isset($_GET["success"]);

    // --- AJAX PROGRESS TELEMETRY ---
    if (isset($_GET['ajax']) && $_GET['ajax'] === 'progress' && is_authed()) {
        while (ob_get_level()) ob_end_clean();
        header('Content-Type: application/json');
        
        $timestamp = $_GET['timestamp'] ?? '';
        $candidate_size = 0;
        $candidate_file = '';
        
        clearstatcache();
        $files = glob($backupDir . "/*");
        
        if ($timestamp && preg_match('/^\d{8}_\d{6}$/', $timestamp)) {
            foreach ($files as $f) {
                if (is_file($f) && strpos(basename($f), $timestamp) !== false) {
                    $s = filesize($f);
                    if ($s > $candidate_size) {
                        $candidate_size = $s;
                        $candidate_file = basename($f);
                    }
                }
            }
        }
        
        echo json_encode([
            'status' => 'success',
            'size' => $candidate_size,
            'size_formatted' => round($candidate_size / (1024 * 1024), 2) . ' MB',
            'file' => $candidate_file,
            'is_final' => (substr($candidate_file, -4) === '.zip')
        ]);
        exit;
    }

    if (isset($_POST["action"])) {


        if ($_POST["action"] === "login") {
            $conf = json_decode(file_get_contents($GLOBALS["authFile"]), true);
            if (password_verify($_POST["pin"], $conf["hash"])) {
                $now = time();
                $token = $now . "." . md5($now . $conf["hash"] . $conf["created_at"]);
                setcookie("cjos_auth_token", $token, time() + 86400, "/");
                header("Location: recovery.php"); exit;
            } else { $msg = "ACCESS DENIED: INVALID CREDENTIALS"; }
        }

        if (is_authed()) {
            set_time_limit(0);
            ini_set('memory_limit', '1024M');

            // --- ACTION: VIEW LOG ---
            if ($_POST["action"] === "view_log") {
                while (ob_get_level()) ob_end_clean();
                header('Content-Type: application/json');
                $zipPath = $backupDir . "/" . $_POST["file"];
                $logData = [];
                $baseFingerprints = [];
                
                $zip = new ZipArchive();
                if ($zip->open($zipPath) === TRUE) {
                    $relData = ltrim(str_replace(CJOS_PATH_ROOT, '', CJOS_PATH_DATA), DIRECTORY_SEPARATOR);
                    $content = $zip->getFromName($relData . "/edit-log-state.json") ?: $zip->getFromName($relData . "/edit-log.json");
                    
                    // 1. Identify Base (Major) for comparison
                    $diffJson = $zip->getFromName('sc_diff.json');
                    if ($diffJson) {
                        $diffMeta = json_decode($diffJson, true);
                        $baseRef = $diffMeta['base_ref'] ?? null;
                        if ($baseRef && file_exists($backupDir . '/' . $baseRef)) {
                            $baseZip = new ZipArchive();
                            if ($baseZip->open($backupDir . '/' . $baseRef) === TRUE) {
                                $baseContent = $baseZip->getFromName($relData . "/edit-log-state.json") ?: $baseZip->getFromName($relData . "/edit-log.json");
                                if ($baseContent) {
                                    $baseLog = json_decode($baseContent, true);
                                    if (is_array($baseLog)) {
                                        foreach ($baseLog as $be) {
                                            $fp = trim($be['date']) . '|' . trim($be['summary']);
                                            $baseFingerprints[] = md5($fp);
                                        }
                                    }
                                }
                                if (!$content) $content = $baseContent;
                                $baseZip->close();
                            }
                        }
                    }

                    if ($content) {
                        $logData = json_decode($content, true);
                        if (is_array($logData)) {
                            if (isset($logData[0]['date']) && isset($logData[1]['date']) && strtotime($logData[0]['date']) < strtotime($logData[1]['date'])) {
                                $logData = array_reverse($logData);
                            }
                            foreach ($logData as &$entry) {
                                $fp = trim($entry['date']) . '|' . trim($entry['summary']);
                                $entry['is_new'] = !empty($baseFingerprints) && !in_array(md5($fp), $baseFingerprints);
                            }
                        }
                    }
                    $zip->close();
                }
                echo json_encode($logData ?: []);
                exit;
            }

            // --- ACTION: RESTORE ---
            if ($_POST["action"] === "restore") {
                $zipPath = $backupDir . "/" . $_POST["file"];
                $isStream = isset($_POST['stream']);
                $skipFolders = isset($_POST['skip_folders']) ? json_decode($_POST['skip_folders'], true) :[];
                
                if ($isStream) {
                    header('Content-Encoding: none');
                    header('X-Accel-Buffering: no');
                    header('Cache-Control: no-cache');
                    while (ob_get_level()) ob_end_clean();
                    ob_implicit_flush(true);
                    header('Content-Type: text/html');
                    echo str_repeat(' ', 4096);
                    
                    $lastError = "Restore Failed";
                    $callback = function($type, $msg, $extra = null) use (&$lastError) {
                        if ($type === 'progress') {
                            echo "<script>window.parent.updateBunkerProgress($msg, " . json_encode($extra) . ");</script>\n";
                            flush();
                        } elseif ($type === 'log' && $extra === 'error') {
                            $lastError = $msg;
                        } elseif ($type === 'task' || $type === 'log') {
                            echo "<script>window.parent.updateBunkerTask(" . json_encode($msg) . ");</script>\n";
                            flush();
                        }
                    };
                    
                    $res = sc_perform_restore($zipPath, $callback, $skipFolders);
                    if ($res) {
                        echo "<script>window.parent.location.href = 'recovery.php?success=1';</script>";
                    } else {
                        echo "<script>window.parent.location.href = 'recovery.php?msg=' + encodeURIComponent(" . json_encode($lastError) . ");</script>";
                    }
                    exit;
                }

                if (file_exists($zipPath)) {
                    $lastError = "Restore Failed";
                    $callback = function($type, $msg, $extra = null) use (&$lastError) {
                        if ($type === 'log' && $extra === 'error') $lastError = $msg;
                    };
                    $clientStateResult = sc_perform_restore($zipPath, $callback, $skipFolders);
                    if ($clientStateResult !== false) {
                        $success = true;
                        if (is_array($clientStateResult)) {
                            $clientState = json_encode($clientStateResult);
                        } else {
                            $clientState = null;
                        }
                    }
                }
            }
            
            // --- ACTION: CREATE ---
            if ($_POST["action"] === "create") {
                $rawName = $_POST["name"] ?? "";
                $name = str_replace(' ', '', ucwords(preg_replace('/[^a-zA-Z0-9]/', ' ', $rawName))) ?: "Manual";
                $timestamp = (!empty($_POST['timestamp']) && preg_match('/^\d{8}_\d{6}$/', $_POST['timestamp'])) ? $_POST['timestamp'] : date('Ymd_His');
                $type = isset($_POST['force_major']) ? 'major' : 'auto';
                $isStream = isset($_POST['stream']);
                
                $zipPath = $backupDir . "/{$timestamp}_{$name}.zip";
                $clientStateStr = $_POST["client_state"] ?? null;

                if ($isStream) {
                    header('Content-Encoding: none');
                    header('X-Accel-Buffering: no');
                    header('Cache-Control: no-cache');
                    while (ob_get_level()) ob_end_clean();
                    ob_implicit_flush(true);
                    header('Content-Type: text/html');
                    echo str_repeat(' ', 4096);
                    
                    $lastError = "Creation Failed";
                    $callback = function($type, $msg, $extra = null) use (&$lastError) {
                        if ($type === 'progress') {
                            echo "<script>window.parent.updateBunkerProgress($msg, " . json_encode($extra) . ");</script>\n";
                            flush();
                        } elseif ($type === 'log' && $extra === 'error') {
                            $lastError = $msg;
                        } elseif ($type === 'task' || $type === 'log') {
                            echo "<script>window.parent.updateBunkerTask(" . json_encode($msg) . ");</script>\n";
                            flush();
                        }
                    };
                    
                    if (sc_perform_create($zipPath, $clientStateStr, $callback, $type)) {
                        echo "<script>window.parent.location.href = 'recovery.php?msg=NEW+CHECKPOINT+SECURED';</script>";
                    } else {
                        echo "<script>window.parent.location.href = 'recovery.php?msg=' + encodeURIComponent(" . json_encode($lastError) . ");</script>";
                    }
                    exit;
                }

                $lastError = "ERROR: Failed to create checkpoint.";
                $callback = function($type, $msg, $extra = null) use (&$lastError) {
                    if ($type === 'log' && $extra === 'error') $lastError = "ERROR: " . $msg;
                };
                if (sc_perform_create($zipPath, $clientStateStr, $callback, $type)) {
                    header("Location: recovery.php?msg=" . urlencode("NEW CHECKPOINT SECURED"));
                    exit;
                } else {
                    $msg = $lastError;
                }
            }// --- ACTION: TOGGLE STAR ---
if ($_POST["action"] === "toggle_star") {
    $meta = file_exists($GLOBALS["metaFile"]) ? json_decode(file_get_contents($GLOBALS["metaFile"]), true) :[];
    $file = $_POST["file"];
    if (isset($meta[$file])) {
        unset($meta[$file]);
    } else {
        $meta[$file] = true;
        // Auto-star Major foundation if this is a Differential
        if (strpos($file, 'DIFF_') === 0) {
$z = new ZipArchive();
if ($z->open($backupDir . "/" . $file) === TRUE) {
    $diffData = json_decode($z->getFromName('sc_diff.json'), true);
    $base = $diffData['base_ref'] ?? null;
    if ($base) $meta[$base] = true;
    $z->close();
}
        }
    }
    file_put_contents($GLOBALS["metaFile"], json_encode($meta));
    if (isset($_POST["ajax"])) {
        while (ob_get_level()) ob_end_clean();
        header('Content-Type: application/json');
        echo json_encode(["status" => "success", "meta" => $meta]);
        exit;
    }
    header("Location: recovery.php"); exit;
}

            // --- ACTION: BULK DELETE ---
if ($_POST["action"] === "bulk_delete") {
    $meta = file_exists($GLOBALS["metaFile"]) ? json_decode(file_get_contents($GLOBALS["metaFile"]), true) : [];
    $files = json_decode($_POST["files"], true);
            
    // Dependency Check
    $allFiles = glob($backupDir . "/*.zip");
    $dependencies =[];
    foreach ($allFiles as $f) {
        $z = new ZipArchive();
        if ($z->open($f) === TRUE) {
            $diffJson = $z->getFromName('sc_diff.json');
            if ($diffJson) {
                $diffMeta = json_decode($diffJson, true);
                if (isset($diffMeta['base_ref'])) {
                    $dependencies[$diffMeta['base_ref']][] = basename($f);
                }
            }
            $z->close();
        }
    }

    $blocked =[];
if (is_array($files)) {
    foreach ($files as $f) {
        $safeFile = basename($f);
        if (isset($dependencies[$safeFile])) {
            $remainingDeps = [];
            foreach ($dependencies[$safeFile] as $dep) {
                if (!in_array($dep, $files)) $remainingDeps[] = $dep;
            }
                        
            if (!empty($remainingDeps) && !isset($_POST['force'])) {
                $blocked[] = $safeFile . " (Blocked by: " . implode(', ', $remainingDeps) . ")";
                continue;
            }
        }
                    
        @unlink($backupDir . "/" . $safeFile);
        if(isset($meta[$safeFile])) unset($meta[$safeFile]);
    }
}
file_put_contents($GLOBALS["metaFile"], json_encode($meta));
            
if (!empty($blocked)) {
    $msg = "DELETION BLOCKED: " . implode(" | ", $blocked);
    header("Location: recovery.php?msg=" . urlencode($msg));
} else {
    header("Location: recovery.php?msg=" . urlencode(count($files) . " CHECKPOINTS PURGED"));
}exit;
}}
    }
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>System Recovery Bunker</title>
    <style>
        :root { --bg: #050505; --card: #121214; --accent: #FF3B30; --text: #E5E5EA; --subtext: #8E8E93; }
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: var(--bg); color: var(--text); margin: 0; display: flex; align-items: center; justify-content: center; height: 100vh; height: 100dvh; overflow: hidden; }
        .container { width: 100%; max-width: 440px; padding: 20px; box-sizing: border-box; animation: fadeIn 0.6s ease-out; display: flex; flex-direction: column; }
        body.list-mode .container { height: 100%; justify-content: flex-start; gap: 10px; }
        @keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
        .header { text-align: center; margin-bottom: 10px; flex-shrink: 0; }
        .logo-box { width: 88px; height: 88px; background: var(--accent); border-radius: 24px; margin: 0 auto 15px; display: flex; align-items: center; justify-content: center; box-shadow: 0 0 40px rgba(255, 59, 48, 0.4); position: relative; }
        .logo-box::after { content: ""; position: absolute; width: 100%; height: 100%; border-radius: 24px; border: 3px solid var(--accent); animation: pulse 2s infinite; }
        @keyframes pulse { 0% { transform: scale(1); opacity: 0.5; } 100% { transform: scale(1.3); opacity: 0; } }
        h1 { font-size: 24px; font-weight: 900; text-transform: uppercase; letter-spacing: 4px; color: var(--accent); margin: 0; }
        .status-tag { font-size: 16px; font-weight: 800; background: rgba(255, 59, 48, 0.1); color: var(--accent); padding: 6px 16px; border-radius: 30px; margin-top: 10px; display: inline-block; border: 2px solid rgba(255, 59, 48, 0.2); letter-spacing: 1px; }
        .card { background: var(--card); border-radius: 20px; padding: 18px; border: 1px solid rgba(255,255,255,0.05); box-shadow: 0 15px 30px rgba(0,0,0,0.4); margin-bottom: 12px; position: relative; overflow: hidden; }
        .card::before { content: ""; position: absolute; top: 0; left: 0; width: 100%; height: 4px; background: linear-gradient(90deg, transparent, var(--accent), transparent); opacity: 0.3; }
        h3 { font-size: 13px; font-weight: 800; margin: 0 0 10px; text-transform: uppercase; letter-spacing: 1px; color: var(--subtext); }
        p { font-size: 12px; color: var(--subtext); line-height: 1.4; margin: 0 0 12px; }
        input { width: 100%; background: var(--input-bg); border: 1px solid var(--border-color); border-radius: 10px; padding: 10px 12px; color: var(--input-text); font-size: 14px; box-sizing: border-box; outline: none; transition: border-color 0.3s; }
        input:focus { border-color: var(--accent); }
        .pin-input { font-size: 20px; text-align: center; letter-spacing: 10px; }
        button { padding: 10px; border-radius: 10px; border: none; font-size: 12px; font-weight: 700; cursor: pointer; transition: all 0.2s; text-transform: uppercase; letter-spacing: 1px; }
        .btn-primary { background: var(--accent); color: var(--primary-text); box-shadow: 0 8px 15px rgba(255, 59, 48, 0.2); width: 100%; }
        .btn-primary:active { transform: scale(0.98); }
        .btn-exit-bar { 
            background: #1c1c1e; 
            color: var(--text); 
            border: 1px solid rgba(255,255,255,0.1); 
            width: 100%; 
            padding: 22px; 
            font-size: 16px; 
            font-weight: 900; 
            border-radius: 24px; 
            margin-top: auto; 
            text-transform: uppercase; 
            letter-spacing: 2px; 
            box-shadow: 0 -10px 30px rgba(0,0,0,0.3);
            cursor: pointer;
            transition: all 0.2s;
            display: block;
            text-align: center;
            text-decoration: none;
            box-sizing: border-box;
            flex-shrink: 0;
        }
        .btn-exit-bar:active { transform: scale(0.97); background: #2c2c2e; }
        .checkpoint-item { display: flex; align-items: center; padding: 10px 0; border-bottom: 1px solid rgba(255,255,255,0.05); gap: 10px; }
        .checkpoint-item:last-child { border-bottom: none; }
        .cp-info { flex: 1; min-width: 0; }
        .cp-name { font-weight: 600; font-size: 14px; margin-bottom: 2px; overflow-wrap: break-word; color: #fff; }
        .cp-meta { font-size: 10px; color: var(--subtext); text-transform: uppercase; }
        .action-group { display: flex; gap: 6px; }
        .btn-mini { padding: 8px 12px; font-size: 10px; border-radius: 8px; background: #222; color: #fff; border: 1px solid #333; }
        .btn-mini.red { color: var(--accent); border-color: rgba(255, 59, 48, 0.2); }
        .btn-mini.blue { color: #007AFF; border-color: rgba(0, 122, 255, 0.2); }
        .btn-mini.gold { color: #FFD60A; border-color: rgba(255, 214, 10, 0.3); }
        .checkpoint-item.starred { background: rgba(255, 214, 10, 0.05); border-left: 2px solid #FFD60A; padding-left: 10px; }
        .checkpoint-item.nested { margin-left: 20px; border-left: 2px solid rgba(255,255,255,0.05); padding-left: 15px; background: rgba(255,255,255,0.01); position: relative; }
        .checkpoint-item.nested.starred { border-left: 2px solid #FFD60A; background: rgba(255, 214, 10, 0.08); }
        .checkpoint-item.starred .btn-mini.gold { background: #FFD60A; color: #000; border-color: #FFD60A; }
        .checkpoint-item.nested::before { content: "└"; position: absolute; left: -12px; top: 15px; color: rgba(255,255,255,0.2); font-size: 14px; }
        .alert { background: rgba(255, 59, 48, 0.1); border: 1px solid var(--accent); color: var(--accent); padding: 12px; border-radius: 12px; font-size: 11px; font-weight: 700; text-align: center; margin-bottom: 20px; text-transform: uppercase; }
        .success-box { text-align: center; }

        /* PROGRESS BAR */
        .bunker-progress-wrap { display: none; margin-top: 24px; margin-bottom: 0; animation: fadeIn 0.3s ease; width: 85%; margin-left: auto; margin-right: auto; }
        .bunker-progress-bar { height: 4px; background: rgba(255,255,255,0.1); border-radius: 10px; overflow: hidden; }
        .bunker-progress-fill { height: 100%; background: var(--accent); width: 0%; transition: width 0.3s ease; box-shadow: 0 0 15px var(--accent), 0 0 5px var(--accent); }
        .bunker-progress-text { font-size: 11px; color: var(--accent); text-transform: uppercase; margin-top: 10px; font-weight: 900; text-align: center; letter-spacing: 2px; text-shadow: 0 0 10px rgba(255, 59, 48, 0.4); }
        
        /* CONTEXT MENU */
        .sc-context-menu { position: fixed; background: #2c2c2e; border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; box-shadow: 0 10px 40px rgba(0,0,0,0.6); z-index: 3000; display: flex; flex-direction: column; padding: 6px; min-width: 140px; animation: fadeIn 0.15s ease-out; }
        .sc-context-menu button { background: transparent; color: var(--text); text-align: left; padding: 12px 14px; border-radius: 8px; font-size: 13px; font-weight: 600; width: 100%; }
        .sc-context-menu button:hover, .sc-context-menu button:active { background: rgba(255,255,255,0.1); }
        
        /* SELECTION UI */
        .checkpoint-item { transition: transform 0.2s; user-select: none; -webkit-user-select: none; }
        .checkpoint-item.sc-menu-active { background: rgba(255, 255, 255, 0.05) !important; border-left: 2px solid var(--accent) !important; }
        .checkpoint-checkbox { display: none; width: 20px; height: 20px; margin-right: 10px; accent-color: var(--accent); }
        body.select-mode .checkpoint-checkbox { display: block; }
        body.select-mode .checkpoint-item { cursor: pointer; }
        
        #bulk-delete-bar {
            display: none; position: fixed; bottom: 20px; left: 50%; transform: translateX(-50%);
            background: var(--card); border: 1px solid var(--accent); padding: 10px 20px;
            border-radius: 50px; box-shadow: 0 10px 30px rgba(0,0,0,0.5); z-index: 1000;
            align-items: center; gap: 15px; animation: slideUp 0.3s ease;
        }
        @keyframes slideUp { from { transform: translateX(-50%) translateY(50px); opacity: 0; } to { transform: translateX(-50%) translateY(0); opacity: 1; } }
        body.select-mode #bulk-delete-bar { display: flex; }
        .log-viewer { display: none; background: #000; border-radius: 12px; padding: 15px; margin-top: 10px; border: 1px solid #222; max-height: 200px; overflow-y: auto; font-family: monospace; font-size: 11px; }
        .log-entry { border-bottom: 1px solid #111; padding: 8px 0; }
        .log-entry:last-child { border-bottom: none; }
        .log-date { color: var(--accent); font-weight: 700; margin-bottom: 2px; }
        
        /* STANDALONE MODAL SYSTEM */
        .modal-overlay { display: none; position: fixed; top: 0; left: 0; right: 0; bottom: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.9); backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px); z-index: 2000; align-items: center; justify-content: center; padding: 20px; box-sizing: border-box; }
        .modal-content { background: #1c1c1e; border: 1px solid rgba(255,255,255,0.1); border-radius: 32px; padding: 35px 25px; width: 100%; max-width: 340px; box-shadow: 0 30px 60px rgba(0,0,0,0.8); text-align: center; position: relative; box-sizing: border-box; margin: auto; }
        .modal-content::before { content: ""; position: absolute; top: 0; left: 50%; transform: translateX(-50%); width: 60px; height: 4px; background: var(--accent); border-radius: 0 0 4px 4px; }
        .modal-title { font-size: 20px; font-weight: 900; color: #fff; margin-bottom: 12px; text-transform: uppercase; letter-spacing: 1.5px; }
        .modal-msg { font-size: 15px; color: var(--subtext); line-height: 1.6; margin-bottom: 30px; }
        .modal-btns { display: flex; flex-direction: column; gap: 10px; }
        .modal-btns button { width: 100%; padding: 16px; font-size: 14px; font-weight: 800; border-radius: 18px; }
        #modal-confirm-btn { order: 1; }
        #modal-cancel-btn { order: 2; background: transparent; border: 1px solid rgba(255,255,255,0.1); color: var(--subtext); }

        /* SUCCESS THEME OVERRIDE */
        body.success-mode { --bg: #081a08; --accent: #34C759; }
        body.success-mode .logo-box { box-shadow: 0 0 30px rgba(52, 199, 89, 0.4); }
        body.success-mode .card::before { background: linear-gradient(90deg, transparent, #34C759, transparent); opacity: 0.6; }
    </style>
    <script>
        function scShowModal(title, msg, onConfirm, isDanger = false, confirmLabel = "Confirm") {
            document.getElementById('modal-title').innerText = title;
            document.getElementById('modal-msg').innerText = msg;
            const btn = document.getElementById('modal-confirm-btn');
            const cancelBtn = document.getElementById('modal-cancel-btn');
            
            btn.innerText = confirmLabel;
            btn.style.background = isDanger ? 'var(--accent)' : '#007AFF';
            btn.onclick = () => { onConfirm(); scCloseModal(); };
            
            if (onConfirm === null) {
                cancelBtn.style.display = 'none';
                btn.parentElement.style.gridTemplateColumns = '1fr';
            } else {
                cancelBtn.style.display = 'block';
                btn.parentElement.style.gridTemplateColumns = '1fr 1fr';
            }

            document.getElementById('modal-overlay').style.display = 'flex';
        }
        function scCloseModal() { document.getElementById('modal-overlay').style.display = 'none'; }

        let scPollInterval = null;
        let scLastSize = 0;
        let scStallCount = 0;
        let scTrackTimestamp = '';

        function startBunkerProgressPolling() {
            if (scPollInterval || !scTrackTimestamp) return;
            scPollInterval = setInterval(async () => {
                try {
                    const res = await fetch(`recovery.php?ajax=progress&timestamp=${scTrackTimestamp}`);
                    const data = await res.json();
                    if (data.status === 'success' && data.size > 0) {
                        const sizeMb = (data.size / (1024 * 1024)).toFixed(2);
                        
                        if (data.is_final) {
                            if (data.size === scLastSize) {
                                scStallCount++;
                                if (scStallCount >= 4) { // Stable for 4 seconds
                                    clearInterval(scPollInterval);
                                    scPollInterval = null;
                                    window.location.href = 'recovery.php?msg=NEW+CHECKPOINT+SECURED';
                                    return;
                                }
                            } else {
                                scLastSize = data.size;
                                scStallCount = 0;
                            }
                        } else {
                            scLastSize = data.size;
                            scStallCount = 0;
                        }
                        
                        updateBunkerProgress(95, `COMPRESSING (${sizeMb} MB / ~${scTargetMb} MB est.)...`);
                    }
                } catch (e) {}
            }, 1000);
        }

        function updateBunkerTask(msg) {
            const text = document.getElementById('bunker-progress-text');
            if (text && msg) text.innerText = msg;
        }

        let scTargetMb = '???';
        function updateBunkerProgress(pct, msg) {
            const wrap = document.getElementById('bunker-progress-wrap');
            const fill = document.getElementById('bunker-progress-fill');
            const text = document.getElementById('bunker-progress-text');
            if (wrap) wrap.style.display = 'block';
            if (fill) fill.style.width = pct + '%';
            
            if (pct === 95 && msg && msg.includes('COMPRESSING_EST:')) {
                scTargetMb = msg.split(':')[1];
                msg = `COMPRESSING (0.00 MB / ~${scTargetMb} MB est.)...`;
                startBunkerProgressPolling();
            }
            
            if (text && msg) text.innerText = msg;
        }

        function prepareCreate(form) {
            let val = form.name.value.trim();
            const now = new Date();
            const defaultName = now.getFullYear() + "-" + String(now.getMonth() + 1).padStart(2, '0') + "-" + String(now.getDate()).padStart(2, '0') + "_" + String(now.getHours()).padStart(2, '0') + String(now.getMinutes()).padStart(2, '0');
            const ts = now.getFullYear() + String(now.getMonth() + 1).padStart(2, '0') + String(now.getDate()).padStart(2, '0') + "_" + String(now.getHours()).padStart(2, '0') + String(now.getMinutes()).padStart(2, '0') + String(now.getSeconds()).padStart(2, '0');
            
            if (!val) {
                form.name.value = defaultName;
            } else {
                form.name.value = val.replace(/[^a-zA-Z0-9\s]/g, ' ')
                                     .split(/\s+/)
                                     .filter(w => w.length > 0)
                                     .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
                                     .join('');
            }
            const state = { localStorage: JSON.stringify(localStorage), cookies: document.cookie };
            form.client_state.value = JSON.stringify(state);
            
            scTrackTimestamp = ts;
            
            let tsInput = form.querySelector('input[name="timestamp"]');
            if (!tsInput) {
                tsInput = document.createElement('input');
                tsInput.type = 'hidden';
                tsInput.name = 'timestamp';
                form.appendChild(tsInput);
            }
            tsInput.value = ts;
            
            // UI Feedback
            updateBunkerProgress(5, "Initializing Creation...");
            startBunkerProgressPolling();
            return true;
        }

        let scLpTimer = null;
        let scStartX = 0, scStartY = 0;
        let scActiveContextFile = null;
        let scActiveContextLogId = null;
        let scJustOpenedMenu = false;

        function scStartLp(e, fileName, logId) {
            if (e.type === 'mousedown' && e.button !== 0) return;
            if (e.touches && e.touches.length > 1) return;
            scStartX = e.touches ? e.touches[0].clientX : e.clientX;
            scStartY = e.touches ? e.touches[0].clientY : e.clientY;
            scLpTimer = setTimeout(() => {
                scOpenContextMenu(e, fileName, logId, scStartX, scStartY);
            }, 500);
        }

        function scMoveLp(e) {
            if (!scLpTimer) return;
            const x = e.touches ? e.touches[0].clientX : e.clientX;
            const y = e.touches ? e.touches[0].clientY : e.clientY;
            if (Math.abs(x - scStartX) > 10 || Math.abs(y - scStartY) > 10) {
                scCancelLp();
            }
        }

        function scCancelLp() {
            if (scLpTimer) { clearTimeout(scLpTimer); scLpTimer = null; }
        }

        function scClearMenuHighlight() {
            document.querySelectorAll('.checkpoint-item.sc-menu-active').forEach(el => {
                el.classList.remove('sc-menu-active');
            });
        }

        function scOpenContextMenu(e, fileName, logId, x = null, y = null) {
            if (e && e.preventDefault) e.preventDefault();
            scCancelLp();
            scClearMenuHighlight();
            scActiveContextFile = fileName;
            scActiveContextLogId = logId;
            scJustOpenedMenu = true;
            setTimeout(() => scJustOpenedMenu = false, 300);

            const item = e ? e.target.closest('.checkpoint-item') : null;
            if (item) item.classList.add('sc-menu-active');

            // Dynamically toggle the log button text based on its visibility
            const logBtn = document.getElementById('sc-ctx-log-btn');
            if (logBtn) {
                const viewer = document.getElementById(logId);
                logBtn.innerText = (viewer && viewer.style.display === "block") ? "Hide Log" : "View Log";
            }

            // Dynamically show the "Select Differentials" button for Major snapshots
            const selectDiffsBtn = document.getElementById('sc-ctx-select-diffs-btn');
            if (selectDiffsBtn) {
                if (fileName.startsWith('MAJOR_')) {
                    let hasDiffs = false;
                    let curr = item ? item.nextElementSibling : null;
                    while (curr) {
                        if (curr.classList.contains('checkpoint-item')) {
                            if (curr.classList.contains('nested')) hasDiffs = true;
                            break;
                        }
                        curr = curr.nextElementSibling;
                    }
                    selectDiffsBtn.style.display = hasDiffs ? 'block' : 'none';
                } else {
                    selectDiffsBtn.style.display = 'none';
                }
            }

            const menu = document.getElementById('sc-context-menu');
            menu.style.display = 'flex';
            
            const px = x !== null ? x : (e.touches ? e.touches[0].clientX : e.clientX);
            const py = y !== null ? y : (e.touches ? e.touches[0].clientY : e.clientY);
            
            let left = px;
            let top = py;
            if (left + 160 > window.innerWidth) left = window.innerWidth - 160;
            if (top + 100 > window.innerHeight) top = window.innerHeight - 100;

            menu.style.left = left + 'px';
            menu.style.top = top + 'px';
            
            if (navigator.vibrate) navigator.vibrate(50);
        }

        document.addEventListener('click', (e) => {
            const menu = document.getElementById('sc-context-menu');
            if (menu && menu.style.display === 'flex' && !menu.contains(e.target)) {
                menu.style.display = 'none';
                scClearMenuHighlight();
            }
        });

        function scCtxRestore() {
            document.getElementById('sc-context-menu').style.display = 'none';
            scClearMenuHighlight();
            if (scActiveContextFile) scConfirmRestore(scActiveContextFile);
        }

        function scCtxLog() {
            document.getElementById('sc-context-menu').style.display = 'none';
            scClearMenuHighlight();
            if (scActiveContextFile && scActiveContextLogId) viewCheckpointLog(scActiveContextFile, scActiveContextLogId);
        }

        function scCtxSelectDiffs() {
            document.getElementById('sc-context-menu').style.display = 'none';
            scClearMenuHighlight();
            
            if (!document.body.classList.contains('select-mode')) {
                scToggleSelectMode();
            }

            if (!scActiveContextFile) return;
            const majorCheckbox = document.querySelector('.checkpoint-checkbox[value="' + scActiveContextFile + '"]');
            if (!majorCheckbox) return;
            
            const majorItem = majorCheckbox.closest('.checkpoint-item');
            let curr = majorItem.nextElementSibling;
            
            while (curr) {
                if (curr.classList.contains('checkpoint-item')) {
                    if (curr.classList.contains('nested')) {
                        const cb = curr.querySelector('.checkpoint-checkbox');
                        if (cb) cb.checked = true;
                    } else {
                        break; // Stop when we reach the next Major or Orphan
                    }
                }
                curr = curr.nextElementSibling;
            }
        }

        async function viewCheckpointLog(fileName, targetId) {
            const viewer = document.getElementById(targetId);
            
            if (viewer.style.display === "block") {
                viewer.style.display = "none";
                return;
            }

            const fd = new FormData();
            fd.append("action", "view_log");
            fd.append("file", fileName);

            viewer.innerHTML = "<div style='color:#666; text-align:center; padding:10px;'>Loading...</div>";
            viewer.style.display = "block";

            try {
                const res = await fetch("recovery.php", { method: "POST", body: fd });
                const data = await res.json();
                
                viewer.innerHTML = "";
                if (data.length === 0) {
                    viewer.innerHTML = "<div style='color:#666; text-align:center;'>No log found in this snapshot.</div>";
                } else {
                    let html = "";
                    let hasNew = false;
                    let hasOld = false;

                    data.forEach(entry => {
                        if (entry.is_new && !hasNew) {
                            html += `<div style="font-size:9px; font-weight:900; color:var(--accent); margin:10px 0 5px 0; text-transform:uppercase; letter-spacing:1px;">New in this Checkpoint</div>`;
                            hasNew = true;
                        }
                        if (!entry.is_new && !hasOld) {
                            html += `<div style="font-size:9px; font-weight:900; color:#555; margin:15px 0 5px 0; text-transform:uppercase; letter-spacing:1px;">Previously Secured</div>`;
                            hasOld = true;
                        }

                        const badge = entry.is_new ? `<span style="background:var(--accent); color:white; font-size:8px; padding:1px 4px; border-radius:3px; margin-left:6px; vertical-align:middle;">NEW</span>` : '';
                        html += `<div class="log-entry" style="${!entry.is_new ? 'opacity:0.5;' : ''}">
                                    <div class='log-date'>${entry.date}${badge}</div>
                                    <div style="font-size:12px;">${entry.summary}</div>
                                 </div>`;
                    });
                    viewer.innerHTML = html;
                }
            } catch(e) {
                scShowModal("System Error", "Failed to retrieve log from snapshot.", null, true, "Close");
                viewer.style.display = "none";
            }
        }

        const protectedAppsList = <?php echo json_encode($protectedAppsList); ?>;
        
        function scConfirmRestore(fileName) {
            if (protectedAppsList && protectedAppsList.length > 0) {
                let html = "<div style='text-align:left; margin-bottom:15px; font-size:13px; color:var(--subtext);'>";
                html += "The following apps are protected. Select any you wish to <strong>OVERWRITE</strong> (revert to snapshot). Unchecked apps will be skipped and keep their live data.</div>";
                html += "<div style='text-align:left; background:rgba(0,0,0,0.2); padding:10px; border-radius:10px; border:1px solid rgba(255,255,255,0.05); margin-bottom:20px;'>";
                protectedAppsList.forEach(app => {
                    html += `<label style='display:flex; align-items:center; gap:10px; margin-bottom:8px; cursor:pointer; color:#fff;'><input type='checkbox' class='bunker-overwrite-cb' value='${app}' style='width:18px; height:18px; accent-color:var(--accent); margin:0;'> Overwrite <strong>${app}</strong></label>`;
                });
                html += "</div>";
                
                scShowModal(
                    "Shielded Apps Detected", 
                    "Placeholder",
                    () => {
                        const overwrites = Array.from(document.querySelectorAll('.bunker-overwrite-cb:checked')).map(cb => cb.value);
                        const skipFolders = protectedAppsList.filter(app => !overwrites.includes(app));
                        executeRestoreForm(fileName, skipFolders);
                    },
                    true,
                    "Confirm & Restore"
                );
                document.getElementById('modal-msg').innerHTML = html; // Override text with HTML
            } else {
                scShowModal(
                    "Rollback System?", 
                    "This will revert all code and configuration to the state of this snapshot. Current changes will be lost.",
                    () => executeRestoreForm(fileName,[]),
                    true,
                    "Restore System"
                );
            }
        }

        function executeRestoreForm(fileName, skipFolders) {
            updateBunkerProgress(5, "Initializing Restore...");
            const f = document.createElement('form');
            f.method = 'POST';
            f.target = 'sc-bunker-worker'; // Target hidden iframe
            const a = document.createElement('input'); a.type='hidden'; a.name='action'; a.value='restore';
            const v = document.createElement('input'); v.type='hidden'; v.name='file'; v.value=fileName;
            const s = document.createElement('input'); s.type='hidden'; s.name='stream'; s.value='1';
            const sk = document.createElement('input'); sk.type='hidden'; sk.name='skip_folders'; sk.value=JSON.stringify(skipFolders);
            f.appendChild(a); f.appendChild(v); f.appendChild(s); f.appendChild(sk);
            document.body.appendChild(f);
            f.submit();
        }

        async function scToggleStar(fileName, btn) {
            btn.style.opacity = '0.5';
            btn.style.pointerEvents = 'none';

            const fd = new FormData();
            fd.append("action", "toggle_star");
            fd.append("file", fileName);
            fd.append("ajax", "1");

            try {
                const res = await fetch("recovery.php", { method: "POST", body: fd });
                const data = await res.json();
                if (data && data.status === "success") {
                    updateStarredStates(data.meta);
                } else {
                    scShowModal("System Error", "Failed to update star state.", null, true, "Close");
                }
            } catch(e) {
                scShowModal("System Error", "Failed to update star state.", null, true, "Close");
            } finally {
                btn.style.opacity = '';
                btn.style.pointerEvents = '';
            }
        }

        function updateStarredStates(meta) {
            document.querySelectorAll('.checkpoint-item').forEach(item => {
                const checkbox = item.querySelector('.checkpoint-checkbox');
                if (!checkbox) return;
                const file = checkbox.value;
                const isStarred = meta[file] === true;
                
                if (isStarred) {
                    item.classList.add('starred');
                } else {
                    item.classList.remove('starred');
                }
                
                const starBtn = item.querySelector('.sc-star-btn');
                if (starBtn) {
                    starBtn.innerText = isStarred ? '★' : '☆';
                }
            });
        }

        function scToggleSelectMode() {
            document.body.classList.toggle('select-mode');
            const btn = document.getElementById('manage-btn');
            btn.innerText = document.body.classList.contains('select-mode') ? 'Cancel' : 'Manage';
            if (!document.body.classList.contains('select-mode')) {
                document.querySelectorAll('.checkpoint-checkbox').forEach(cb => cb.checked = false);
            }
        }

        function confirmBulkDelete(force = false) {
            const selected = Array.from(document.querySelectorAll('.checkpoint-checkbox:checked')).map(cb => cb.value);
            if (selected.length === 0) return;
            
            const title = force ? "FORCE PURGE?" : "Purge Checkpoints?";
            const msg = force 
                ? `DANGER: You are forcing the deletion of ${selected.length} snapshots. This will break any Differential checkpoints that depend on them. Proceed?`
                : `Permanently delete ${selected.length} selected snapshots? This cannot be undone.`;

            scShowModal(
                title, 
                msg,
                () => {
                    const f = document.createElement('form');
                    f.method = 'POST';
                    const a = document.createElement('input'); a.type='hidden'; a.name='action'; a.value='bulk_delete';
                    const v = document.createElement('input'); v.type='hidden'; v.name='files'; v.value=JSON.stringify(selected);
                    if (force) {
                        const frc = document.createElement('input'); frc.type='hidden'; frc.name='force'; frc.value='1';
                        f.appendChild(frc);
                    }
                    f.appendChild(a); f.appendChild(v);
                    document.body.appendChild(f);
                    f.submit();
                },
                true,
                force ? "Force Delete" : "Confirm"
            );
        }
    </script>
</head>
<body class="<?php 
    if ($success) echo 'success-mode '; 
    if (is_authed() && !$success) echo 'list-mode '; 
?>">
    <div class="container">
        <?php if (!$success): ?>
            <div class="header">
                <div class="logo-box">
                    <svg width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>
                </div>
                <h1>Recovery Bunker</h1>
                <div class="status-tag">SYSTEM ISOLATION ACTIVE</div>
                
                <div id="bunker-progress-wrap" class="bunker-progress-wrap">
                    <div class="bunker-progress-bar">
                        <div id="bunker-progress-fill" class="bunker-progress-fill"></div>
                    </div>
                    <div id="bunker-progress-text" class="bunker-progress-text">Processing...</div>
                </div>
            </div>

            <?php if ($msg): ?>
                <div class="alert"><?php echo $msg; ?></div>
            <?php endif; ?>
        <?php endif; ?>

        <?php if ($success): ?>
            <div class="card success-box" style="padding: 40px 25px;">
                <div class="logo-box" style="margin-bottom: 25px; background: var(--accent);">
                    <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2.5"><path d="M20 6L9 17l-5-5"/></svg>
                </div>
                <h1 style="font-size: 24px; color: #fff; margin-bottom: 10px; letter-spacing: 1px;">System Restored</h1>
                <p style="font-size: 14px; opacity: 0.8; margin-bottom: 30px;">Environment and browser state successfully reverted to the selected checkpoint.</p>
                
                <div style="display:flex; flex-direction:column; gap:12px;">
                    <button class="btn-primary" style="padding: 20px;" onclick="window.location.href='index.php'">Initialize App</button>
                    <button class="btn-exit-bar" style="background: transparent; border: 1px solid rgba(255,255,255,0.1); font-size: 12px; padding: 15px;" onclick="window.location.href='recovery.php'">Return to Bunker</button>
                </div>
                <?php if ($clientState): ?>
                <script>
                    const state = <?php echo $clientState; ?>;
                    const isTokenKey = (k) => k.toLowerCase().includes('token') || k.toLowerCase().includes('auth') || k.toLowerCase().includes('vault');
                    
                    if(state.localStorage) { 
                        const oldKeys = Object.keys(localStorage);
                        oldKeys.forEach(k => { if(!isTokenKey(k)) localStorage.removeItem(k); });
                        const snapLS = JSON.parse(state.localStorage); 
                        for(let k in snapLS) {
                            if(!isTokenKey(k) || !localStorage.getItem(k)) localStorage.setItem(k, snapLS[k]);
                        }
                    }
                    if(state.cookies) { 
                        state.cookies.split(";").forEach(c => { 
                            const name = c.split("=")[0].trim();
                            if(!isTokenKey(name)) document.cookie = c.trim() + "; path=/; max-age=31536000"; 
                        }); 
                    }
                </script>
                <?php endif; ?>
                <script>
                    if (window.history.replaceState) { window.history.replaceState(null, null, window.location.pathname); }
                </script>
            </div>
        <?php elseif (!is_authed()): ?>
            <div class="card">
                <h3>Identity Required</h3>
                <p>Authorize system-level access to initiate recovery protocols.</p>
                <form method="POST">
                    <input type="hidden" name="action" value="login">
                    <input type="password" name="pin" class="pin-input" placeholder="••••" inputmode="numeric" pattern="[0-9]*" required autofocus>
                    <button type="submit" class="btn-primary" style="margin-top:20px;">Unlock Bunker</button>
                </form>
            </div>
        <?php else: ?>
            <div class="card" style="margin-bottom: 10px;">
    <h3 style="display:flex; justify-content:space-between; align-items:center;">
        Create Snapshot
        <span style="font-size: 9px; opacity: 0.5; font-weight: 400; text-transform: none;"><?php echo date('H:i:s'); ?></span>
    </h3>
    <form method="POST" onsubmit="return prepareCreate(this)" target="sc-bunker-worker">
        <input type="hidden" name="action" value="create">
        <input type="hidden" name="stream" value="1">
        <input type="hidden" name="client_state" value="">
        <div style="display:flex; gap:8px; margin-bottom:8px;">
            <input type="text" name="name" placeholder="Label (Optional)..." style="flex:1;">
            <button type="submit" class="btn-primary" style="width:auto; padding-left:20px; padding-right:20px;">Secure</button>
        </div>
        <label style="display:flex; align-items:center; gap:6px; font-size:10px; color:var(--subtext); cursor:pointer; opacity:0.7;">
            <input type="checkbox" name="force_major" value="1" style="width:14px; height:14px; margin:0;">
            Force Major Snapshot (Full Backup)
        </label>
    </form>
</div>
<div class="card" style="flex: 1; min-height: 0; display: flex; flex-direction: column; margin-bottom: 0;">
    <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:10px; flex-shrink: 0;">
        <h3 style="margin:0;">Checkpoints</h3>
        <button id="manage-btn" onclick="scToggleSelectMode()" style="background:none; border:none; color:var(--accent); font-size:11px; font-weight:800; text-transform:uppercase; padding:0; cursor:pointer;">Manage</button>
    </div>
    <div style="flex: 1; overflow-y: auto; padding-right: 5px; border-top: 1px solid rgba(255,255,255,0.03);"><?php 
    $meta = file_exists($backupDir . "/meta.json") ? json_decode(file_get_contents($backupDir . "/meta.json"), true) :[];
    $allFiles = glob($backupDir . "/*.zip");
                    
    $tree = [];
    $orphans = [];
                    
    // 1. Identify Majors
    foreach ($allFiles as $f) {
        $n = basename($f);
        if (strpos($n, 'MAJOR_') === 0) {
            $tree[$n] = ['file' => $f, 'name' => $n, 'diffs' => []];
        }
    }
                    
    // 2. Map Differentials
    foreach ($allFiles as $f) {
        $n = basename($f);
        if (strpos($n, 'DIFF_') === 0) {
            $z = new ZipArchive(); $base = null;
            if ($z->open($f) === TRUE) {
                $diffData = json_decode($z->getFromName('sc_diff.json'), true);
                $base = $diffData['base_ref'] ?? null;
                $z->close();
            }
            if ($base && isset($tree[$base])) {
                $tree[$base]['diffs'][] = ['file' => $f, 'name' => $n];
            } else {
                $orphans[] = ['file' => $f, 'name' => $n, 'base' => $base];
            }
        } elseif (strpos($n, 'MAJOR_') !== 0) {
            $orphans[] = ['file' => $f, 'name' => $n]; // Legacy
        }
    }

    // 3. Sort Tree (Newest Major First)
    uksort($tree, function($a, $b) { return strcmp($b, $a); });
    // Sort Diffs within Majors (Newest First)
    foreach ($tree as &$node) {
        usort($node['diffs'], function($a, $b) { return strcmp($b['name'], $a['name']); });
    }
    // Sort Orphans
    usort($orphans, function($a, $b) { return strcmp($b['name'], $a['name']); });

    // 4. Flatten for Rendering
    $renderList = [];
    foreach ($tree as $major) {
        $renderList[] = array_merge($major, ['nested' => false]);
        foreach ($major['diffs'] as $diff) {
            $renderList[] = array_merge($diff, ['nested' => true]);
        }
    }
    foreach ($orphans as $o) {
        $renderList[] = array_merge($o, ['nested' => false]);
    }

    if (empty($renderList)): echo "<div style='color:#444; text-align:center; padding:20px;'>No data found.</div>"; else:
    foreach ($renderList as $item): 
    $f = $item['file'];
    $n = $item['name']; 
    $d = date("M j, H:i:s", filemtime($f)); 
    $label = str_replace(".zip","", $n);$label = preg_replace('/^(MAJOR|DIFF)_\d{8}_\d{6}_/', '', $label);
        if (strpos($n, '17') === 0 || strpos($n, '20') === 0) $label = str_replace(".zip","",substr($n,15));
        $isMajor = strpos($n, 'MAJOR_') === 0;
        $isDiff = strpos($n, 'DIFF_') === 0;
        $isStarred = isset($meta[$n]);
        $isNested = $item['nested'] ?? false;
        $baseRef = $item['base'] ?? null;
    ?>
        <div class="checkpoint-item <?php echo $isStarred ? 'starred' : ''; ?> <?php echo $isNested ? 'nested' : ''; ?>" 
             oncontextmenu="scOpenContextMenu(event, '<?php echo $n; ?>', 'log-<?php echo md5($n); ?>')"
             ontouchstart="scStartLp(event, '<?php echo $n; ?>', 'log-<?php echo md5($n); ?>')"
             ontouchmove="scMoveLp(event)"
             ontouchend="scCancelLp()"
             onmousedown="scStartLp(event, '<?php echo $n; ?>', 'log-<?php echo md5($n); ?>')"
             onmousemove="scMoveLp(event)"
             onmouseup="scCancelLp()"
             onmouseleave="scCancelLp()"
             onclick="if(scJustOpenedMenu) return; if(document.body.classList.contains('select-mode')) this.querySelector('.checkpoint-checkbox').click()"><input type="checkbox" class="checkpoint-checkbox" value="<?php echo $n; ?>" onclick="event.stopPropagation()">
        <div class="cp-info">
            <div class="cp-name">
                <?php if ($isMajor): ?>
                    <span style="font-size:8px; background:var(--accent); color:white; padding:2px 4px; border-radius:3px; vertical-align:middle; margin-right:4px;">MAJOR</span>
                <?php elseif (strpos($n, 'DIFF_') === 0): ?>
                    <span style="font-size:8px; background:#007AFF; color:white; padding:2px 4px; border-radius:3px; vertical-align:middle; margin-right:4px;">DIFF</span>
                <?php endif; ?>
                <?php echo $label; ?>
                <?php if ($baseRef): ?>
                    <span style="font-size:8px; background:rgba(255,255,255,0.1); color:var(--subtext); padding:2px 4px; border-radius:3px; vertical-align:middle; margin-left:4px;">Base: <?php echo substr($baseRef, 0, 12); ?>...</span>
                <?php endif; ?>
            </div>
            <div class="cp-meta"><?php echo $d; ?></div>
        </div><div class="action-group" onclick="event.stopPropagation()" onmousedown="event.stopPropagation()" ontouchstart="event.stopPropagation()">
                                <button type="button" class="btn-mini gold sc-star-btn" onclick="scToggleStar('<?php echo $n; ?>', this)"><?php echo $isStarred ? '★' : '☆'; ?></button>
                            </div>
                        </div>
                        <div id="log-<?php echo md5($n); ?>" class="log-viewer"></div>
                    <?php endforeach; endif; ?>
                </div>
            </div>

            <div id="bulk-delete-bar">
                <span style="font-size:12px; font-weight:700; color:var(--accent);">Selection Mode</span>
                <div style="display:flex; gap:8px;">
                    <button onclick="confirmBulkDelete()" style="background:var(--accent); color:white; padding:8px 15px; border-radius:20px; font-size:11px;">Delete Selected</button>
                </div>
            </div>
            <a href="index.php" class="btn-exit-bar">Exit to Mainframe</a>
        <?php endif; ?>
    </div>

    <!-- CONTEXT MENU -->
    <div id="sc-context-menu" class="sc-context-menu" style="display:none;">
        <button onclick="scCtxRestore()">Restore Snapshot</button>
        <button id="sc-ctx-log-btn" onclick="scCtxLog()">View Log</button>
        <button id="sc-ctx-select-diffs-btn" onclick="scCtxSelectDiffs()" style="display:none; color:var(--accent);">Select Differentials</button>
    </div>

    <!-- MODAL OVERLAY -->
    <div id="modal-overlay" class="modal-overlay" onclick="if(event.target===this) scCloseModal()">
        <div class="modal-content">
            <div id="modal-title" class="modal-title">Confirm Action</div>
            <div id="modal-msg" class="modal-msg">Are you sure you want to proceed?</div>
            <div class="modal-btns">
                <button id="modal-cancel-btn" class="btn-ghost" onclick="scCloseModal()" style="margin:0;">Cancel</button>
                <button id="modal-confirm-btn" class="btn-primary">Confirm</button>
            </div>
        </div>
    </div>
    <!-- HIDDEN WORKER IFRAME -->
    <iframe name="sc-bunker-worker" id="sc-bunker-worker" style="display:none;"></iframe>
</body>
</html>
PHP;

    file_put_contents(CJOS_PATH_ROOT . '/recovery.php', $code);
}