<?php
if (!defined('CJOS_PATH_ROOT')) {
    exit('No direct script access allowed');
}

require_once __DIR__ . '/db.php';

$action = $_GET['ajax'] ?? $_POST['ajax'] ?? '';

if (!$action) {
    return; // Not an API request
}

// JIT Template Propagation
function propagate_ssot_templates() {
    $sync_file = __DIR__ . '/../data/template_sync.json';
    if (!file_exists($sync_file)) {
        return; // Rely exclusively on template_sync.json as the Single Source of Truth
    }

    $sync_map = json_decode(file_get_contents($sync_file), true);
    if (!$sync_map) return;

    $base_dir = realpath(__DIR__ . '/..');

    foreach ($sync_map as $master_rel => $dest_rel_list) {
        $master_abs = $base_dir . '/' . $master_rel;
        if (!file_exists($master_abs)) continue;

        $master_content = file_get_contents($master_abs);
        $ext = pathinfo($master_abs, PATHINFO_EXTENSION);

        $warning = "";
        if ($ext === 'java' || ($ext === 'tpl' && strpos($master_rel, '.java') !== false)) {
            $warning = "// ============================================================================\n"
                     . "// ⚠️ WARNING: DO NOT EDIT THIS FILE DIRECTLY!\n"
                     . "// This is a dynamically synchronized child template.\n"
                     . "// All modifications must be made strictly to the master template at:\n"
                     . "// apps/ApkStudio/" . $master_rel . "\n"
                     . "// ============================================================================\n\n";
        } elseif ($ext === 'xml' || ($ext === 'tpl' && strpos($master_rel, '.xml') !== false) || $ext === 'html' || ($ext === 'tpl' && strpos($master_rel, '.html') !== false)) {
            $warning = "<!--\n"
                     . "============================================================================\n"
                     . "⚠️ WARNING: DO NOT EDIT THIS FILE DIRECTLY!\n"
                     . "This is a dynamically synchronized child template.\n"
                     . "All modifications must be made strictly to the master template at:\n"
                     . "apps/ApkStudio/" . $master_rel . "\n"
                     . "============================================================================\n"
                     . "-->\n\n";
        }

        foreach ($dest_rel_list as $dest_rel) {
            $dest_abs = $base_dir . '/' . $dest_rel;
            $dest_dir = dirname($dest_abs);

            if (is_dir($dest_dir)) {
                if (!empty($warning) && ($ext === 'xml' || strpos($master_rel, '.xml') !== false)) {
                    if (preg_match('/^\s*(<\?xml[^>]*\?>)/i', $master_content, $matches)) {
                        $xml_decl = $matches[1];
                        $body = substr($master_content, strlen($matches[0]));
                        $final_content = $xml_decl . "\n" . $warning . ltrim($body);
                    } else {
                        $final_content = $warning . $master_content;
                    }
                } else {
                    $final_content = $warning . $master_content;
                }

                if (!file_exists($dest_abs) || file_get_contents($dest_abs) !== $final_content) {
                    file_put_contents($dest_abs, $final_content);
                }
            }
        }
    }
}

// Run dynamic master template propagation on every API request
propagate_ssot_templates();

// Adaptive Path Resolver
function get_project_dir($name, $id) {
    $safe_name = preg_replace('/[^a-zA-Z0-9_-]/', '', $name);
    $path1 = __DIR__ . "/../data/projects/{$safe_name}";
    $path2 = __DIR__ . "/../data/projects/{$safe_name}_{$id}";
    if (is_dir($path1)) {
        return realpath($path1);
    }
    if (is_dir($path2)) {
        return realpath($path2);
    }
    return false;
}

// Two-Way Filesystem Sync Engine
function sync_projects_from_filesystem($db) {
    $projects_dir = __DIR__ . '/../data/projects';
    if (!is_dir($projects_dir)) {
        mkdir($projects_dir, 0777, true);
        return;
    }
    
    $dirs = glob($projects_dir . '/*', GLOB_ONLYDIR);
    $active_ids = [];
    
    foreach ($dirs as $dir) {
        $folder_name = basename($dir);
        if (strpos($folder_name, '.') === 0) continue;
        
        $id_part = null;
        $name_part = $folder_name;
        
        // Parse legacy suffix if present
        if (preg_match('/^(.+)_(\d+)$/', $folder_name, $matches)) {
            $name_part = $matches[1];
            $id_part = (int)$matches[2];
        }
        
        // Inspect AndroidManifest to automatically recover package names
        $pkg = 'com.example.' . strtolower(preg_replace('/[^a-zA-Z0-9]/', '', $name_part));
        $manifest_path = "$dir/AndroidManifest.xml";
        if (file_exists($manifest_path)) {
            $manifest_content = file_get_contents($manifest_path);
            if (preg_match('/package="([^"]+)"/', $manifest_content, $pkg_matches)) {
                $pkg = $pkg_matches[1];
            }
        }
        
        if ($id_part !== null) {
            $stmt = $db->prepare("SELECT COUNT(*) FROM projects WHERE id = ?");
            $stmt->execute([$id_part]);
            if ($stmt->fetchColumn() == 0) {
                $stmt = $db->prepare("INSERT INTO projects (id, name, package_name) VALUES (?, ?, ?)");
                $stmt->execute([$id_part, $name_part, $pkg]);
            }
            $active_ids[] = $id_part;
        } else {
            $stmt = $db->prepare("SELECT id FROM projects WHERE name = ?");
            $stmt->execute([$name_part]);
            $row = $stmt->fetch();
            if (!$row) {
                // Auto-register newly patched folders
                $stmt = $db->prepare("INSERT INTO projects (name, package_name) VALUES (?, ?)");
                $stmt->execute([$name_part, $pkg]);
                $active_ids[] = $db->lastInsertId();
            } else {
                $active_ids[] = $row['id'];
            }
        }
    }
    
    // Prune orphans
    $stmt = $db->query("SELECT id, name FROM projects");
    $db_projects = $stmt->fetchAll();
    foreach ($db_projects as $p) {
        if (!in_array($p['id'], $active_ids)) {
            $safe_name = preg_replace('/[^a-zA-Z0-9_-]/', '', $p['name']);
            $path1 = $projects_dir . '/' . $safe_name;
            $path2 = $projects_dir . '/' . $safe_name . '_' . $p['id'];
            if (!is_dir($path1) && !is_dir($path2)) {
                $db->prepare("DELETE FROM projects WHERE id = ?")->execute([$p['id']]);
            }
        }
    }
}

function delete_dir($dir) {
    if (!is_dir($dir)) return;
    $files = array_diff(scandir($dir), ['.', '..']);
    foreach ($files as $file) {
        (is_dir("$dir/$file")) ? delete_dir("$dir/$file") : unlink("$dir/$file");
    }
    rmdir($dir);
}

function prune_empty_dirs($dir, $stop_at) {
    if (!is_dir($dir) || realpath($dir) === realpath($stop_at)) return;
    $files = array_diff(scandir($dir), ['.', '..']);
    if (empty($files)) {
        rmdir($dir);
        prune_empty_dirs(dirname($dir), $stop_at);
    }
}

function get_project_last_modified($dir) {
    if (!is_dir($dir)) return 0;
    $max_mtime = filemtime($dir);
    try {
        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($dir, RecursiveDirectoryIterator::SKIP_DOTS),
            RecursiveIteratorIterator::SELF_FIRST
        );
        foreach ($iterator as $file) {
            if ($file->isFile()) {
                $mtime = $file->getMTime();
                if ($mtime > $max_mtime) {
                    $max_mtime = $mtime;
                }
            }
        }
    } catch (Exception $e) {
        // Fallback safely
    }
    return $max_mtime;
}

// JIT Template Hydration (SSOT Enforcement)
function enforce_ssot_templates($proj, $proj_dir) {
    // Force template propagation at the start of the build/packaging pipeline
    propagate_ssot_templates();

    $tpl_dir = __DIR__ . "/../templates";
    $replacements = [
        '{{APP_NAME}}' => $proj['name'], 
        '{{PACKAGE_NAME}}' => $proj['package_name'],
        '{{WRAPPER_URL}}' => $proj['wrapper_url'] ?? '',
        '{{DOWNLOAD_URL}}' => ''
    ];
    
    $pkg_path = "$proj_dir/src/" . str_replace('.', '/', $proj['package_name']);
    if (!is_dir($pkg_path)) mkdir($pkg_path, 0777, true);
    if (!is_dir("$proj_dir/res/values")) mkdir("$proj_dir/res/values", 0777, true);
    
    if (($proj['project_type'] ?? '') === 'wrapper') {
        $manifest_content = file_get_contents("$tpl_dir/AndroidManifest_wrapper.xml.tpl");
        $hydrated_manifest = strtr($manifest_content, $replacements);
        
        // Dynamically recover/preserve custom launcher icon attributes if the asset exists on disk!
        $drawable_dir = "$proj_dir/res/drawable";
        if (is_dir($drawable_dir)) {
            $files = glob("$drawable_dir/*.png");
            if (!empty($files)) {
                $icon_name = pathinfo($files[0], PATHINFO_FILENAME);
                if (strpos($hydrated_manifest, 'android:icon=') !== false) {
                    $hydrated_manifest = preg_replace('/android:icon="[^"]+"/', 'android:icon="@drawable/' . $icon_name . '"', $hydrated_manifest);
                } else {
                    $hydrated_manifest = preg_replace('/<application/i', '<application android:icon="@drawable/' . $icon_name . '"', $hydrated_manifest);
                }
            }
        }
        
        file_put_contents("$proj_dir/AndroidManifest.xml", $hydrated_manifest);
        file_put_contents("$pkg_path/MainActivity.java", strtr(file_get_contents("$tpl_dir/MainActivity_wrapper.java.tpl"), $replacements));
        if (!is_dir("$proj_dir/assets")) mkdir("$proj_dir/assets", 0777, true);
        if (file_exists("$tpl_dir/settings.html.tpl")) {
            file_put_contents("$proj_dir/assets/settings.html", strtr(file_get_contents("$tpl_dir/settings.html.tpl"), $replacements));
        }
    }
    
    // Always JIT-hydrate strings.xml if missing
    if (!file_exists("$proj_dir/res/values/strings.xml")) {
        file_put_contents("$proj_dir/res/values/strings.xml", strtr(file_get_contents("$tpl_dir/strings.xml.tpl"), $replacements));
    }
    // Only JIT-hydrate build.sh always for wrapper projects, or if it doesn't exist for standard projects (preserving custom builds like BuildKernel)
    if (($proj['project_type'] ?? '') === 'wrapper' || !file_exists("$proj_dir/build.sh")) {
        file_put_contents("$proj_dir/build.sh", strtr(file_get_contents("$tpl_dir/build.sh.tpl"), $replacements));
        chmod("$proj_dir/build.sh", 0755);
    }
}

header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
header('Access-Control-Allow-Headers: *');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit;
}

switch ($action) {
    case 'get_projects':
    case 'get_build_commands':
    case 'get_apps':
        sync_projects_from_filesystem($db);
        $stmt = $db->query("SELECT * FROM projects ORDER BY name ASC");
        $projects = $stmt->fetchAll();
        
        $protocol = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https')) ? "https" : "http";
        $host = $_SERVER['HTTP_HOST'] ?? '127.0.0.1:8000';
        if (strpos($host, ':') === false) {
            $port = $_SERVER['SERVER_PORT'] ?? $_SERVER['HTTP_X_FORWARDED_PORT'] ?? null;
            if ($port && (($protocol === 'https' && $port != 443) || ($protocol === 'http' && $port != 80))) {
                $host .= ':' . $port;
            }
        }
        $script_uri = explode('?', $_SERVER['REQUEST_URI'] ?? '/apps/ApkStudio/index.php')[0];
        $base_download_url = $protocol . "://" . $host . $script_uri;

        foreach ($projects as &$p) {
            $p['icon_url'] = null;
            $p['download_url'] = $base_download_url . "?ajax=download_zip&id=" . $p['id'];
            $p['build_command'] = 'rm -rf ~/apk_build && mkdir -p ~/apk_build && cd ~/apk_build && curl -fsSLk "' . $p['download_url'] . '" -o project.zip && unzip -oq project.zip && chmod +x build.sh && AUTO_EXIT=1 bash ./build.sh';

            $proj_dir = get_project_dir($p['name'], $p['id']);
            if ($proj_dir) {
                $manifest_path = $proj_dir . '/AndroidManifest.xml';
                $icon_name = 'app_icon';
                if (file_exists($manifest_path)) {
                    $manifest = file_get_contents($manifest_path);
                    if (preg_match('/android:icon="@drawable\/([a-zA-Z0-9_]+)"/', $manifest, $matches)) {
                        $icon_name = $matches[1];
                    }
                }
                
                $icon_abs = $proj_dir . "/res/drawable/{$icon_name}.png";
                if (file_exists($icon_abs)) {
                    $p['icon_url'] = 'data:image/png;base64,' . base64_encode(file_get_contents($icon_abs));
                }
            }
        }
        echo json_encode(['success' => true, 'projects' => $projects]);
        break;

    case 'get_recent_projects_text':
        sync_projects_from_filesystem($db);
        $stmt = $db->query("SELECT * FROM projects");
        $projects = $stmt->fetchAll();
        
        $sorted_projects = [];
        foreach ($projects as $p) {
            $proj_dir = get_project_dir($p['name'], $p['id']);
            if ($proj_dir) {
                $mtime = get_project_last_modified($proj_dir);
                $sorted_projects[] = [
                    'id' => $p['id'],
                    'name' => $p['name'],
                    'mtime' => $mtime
                ];
            }
        }
        
        usort($sorted_projects, function($a, $b) {
            return $b['mtime'] - $a['mtime'];
        });
        
        $top_5 = array_slice($sorted_projects, 0, 5);
        header('Content-Type: text/plain; charset=UTF-8');
        foreach ($top_5 as $index => $p) {
            echo ($index + 1) . "|" . $p['name'] . "|" . $p['id'] . "\n";
        }
        exit;

    case 'create_project':
        $name = trim($_POST['name'] ?? '');
        $pkg = trim($_POST['package_name'] ?? '');
        $type = trim($_POST['project_type'] ?? 'standard');
        $url = trim($_POST['wrapper_url'] ?? '');
        
        if (!$name || !$pkg) {
            echo json_encode(['success' => false, 'error' => 'Missing name or package']);
            exit;
        }
        
        $stmt = $db->prepare("INSERT INTO projects (name, package_name, project_type, wrapper_url) VALUES (?, ?, ?, ?)");
        $stmt->execute([$name, $pkg, $type, $url]);
        $id = $db->lastInsertId();
        
        $safe_name = preg_replace('/[^a-zA-Z0-9_-]/', '', $name);
        $proj_dir = __DIR__ . "/../data/projects/{$safe_name}";
        if (is_dir($proj_dir)) {
            $proj_dir .= "_{$id}";
        }
        
        mkdir("$proj_dir/src/" . str_replace('.', '/', $pkg), 0777, true);
        mkdir("$proj_dir/res/values", 0777, true);
        mkdir("$proj_dir/assets", 0777, true);
        
        $tpl_dir = __DIR__ . "/../templates";
        $replacements = [
            '{{APP_NAME}}' => $name, 
            '{{PACKAGE_NAME}}' => $pkg,
            '{{WRAPPER_URL}}' => $url,
            '{{DOWNLOAD_URL}}' => ''
        ];
        
        file_put_contents("$proj_dir/res/values/strings.xml", strtr(file_get_contents("$tpl_dir/strings.xml.tpl"), $replacements));
        file_put_contents("$proj_dir/build.sh", strtr(file_get_contents("$tpl_dir/build.sh.tpl"), $replacements));
        chmod("$proj_dir/build.sh", 0755);

        if ($type === 'wrapper') {
            // Deploy clean WebView Wrapper templates
            file_put_contents("$proj_dir/AndroidManifest.xml", strtr(file_get_contents("$tpl_dir/AndroidManifest_wrapper.xml.tpl"), $replacements));
            file_put_contents("$proj_dir/src/" . str_replace('.', '/', $pkg) . "/MainActivity.java", strtr(file_get_contents("$tpl_dir/MainActivity_wrapper.java.tpl"), $replacements));
            if (file_exists("$tpl_dir/settings.html.tpl")) {
                file_put_contents("$proj_dir/assets/settings.html", strtr(file_get_contents("$tpl_dir/settings.html.tpl"), $replacements));
            }
        } else {
            // Deploy Standard Java Layout templates
            mkdir("$proj_dir/res/layout", 0777, true);
            file_put_contents("$proj_dir/AndroidManifest.xml", strtr(file_get_contents("$tpl_dir/AndroidManifest.xml.tpl"), $replacements));
            file_put_contents("$proj_dir/src/" . str_replace('.', '/', $pkg) . "/MainActivity.java", strtr(file_get_contents("$tpl_dir/MainActivity.java.tpl"), $replacements));
            file_put_contents("$proj_dir/res/layout/activity_main.xml", strtr(file_get_contents("$tpl_dir/activity_main.xml.tpl"), $replacements));
        }
        
        echo json_encode(['success' => true]);
        break;

    case 'edit_project':
        $id = (int)($_POST['id'] ?? 0);
        $new_name = trim($_POST['name'] ?? '');
        $new_pkg = trim($_POST['package_name'] ?? '');

        if (!$id || !$new_name || !$new_pkg) {
            echo json_encode(['success' => false, 'error' => 'Missing ID, name, or package name']);
            exit;
        }

        $stmt = $db->prepare("SELECT * FROM projects WHERE id = ?");
        $stmt->execute([$id]);
        $proj = $stmt->fetch();
        if (!$proj) {
            echo json_encode(['success' => false, 'error' => 'Project not found']);
            exit;
        }

        $old_name = $proj['name'];
        $old_pkg = $proj['package_name'];
        $old_dir = get_project_dir($old_name, $id);

        if (!$old_dir || !is_dir($old_dir)) {
            echo json_encode(['success' => false, 'error' => 'Original project directory missing']);
            exit;
        }

        // 1. Rename the project directory on disk if needed
        $new_safe_name = preg_replace('/[^a-zA-Z0-9_-]/', '', $new_name);
        $new_dir = __DIR__ . "/../data/projects/{$new_safe_name}";
        if (is_dir($new_dir) && realpath($new_dir) !== realpath($old_dir)) {
            $new_dir .= "_{$id}";
        }

        if (realpath($old_dir) !== realpath($new_dir)) {
            if (!rename($old_dir, $new_dir)) {
                echo json_encode(['success' => false, 'error' => 'Failed to rename project folder on disk']);
                exit;
            }
        }

        $new_dir = realpath($new_dir);

        // 2. Reorganize Java packages: Move files to the new package directory
        if ($old_pkg !== $new_pkg) {
            $old_pkg_path = $new_dir . "/src/" . str_replace('.', '/', $old_pkg);
            $new_pkg_path = $new_dir . "/src/" . str_replace('.', '/', $new_pkg);

            if (is_dir($old_pkg_path)) {
                if (!is_dir($new_pkg_path)) {
                    mkdir($new_pkg_path, 0777, true);
                }
                $files = array_diff(scandir($old_pkg_path), ['.', '..']);
                foreach ($files as $file) {
                    rename("$old_pkg_path/$file", "$new_pkg_path/$file");
                }
                prune_empty_dirs($old_pkg_path, $new_dir . "/src");
            }
        }

        // 3. Update Database row
        $stmt = $db->prepare("UPDATE projects SET name = ?, package_name = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?");
        $stmt->execute([$new_name, $new_pkg, $id]);

        $stmt = $db->prepare("SELECT * FROM projects WHERE id = ?");
        $stmt->execute([$id]);
        $updated_proj = $stmt->fetch();

        // 4. Find & Replace package name inside source code files recursively (Code Refactoring)
        $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($new_dir));
        foreach ($iterator as $file) {
            if ($file->isFile()) {
                $filePath = $file->getRealPath();
                $ext = pathinfo($filePath, PATHINFO_EXTENSION);
                if (in_array($ext, ['java', 'xml', 'sh', 'tpl'])) {
                    $content = file_get_contents($filePath);
                    $updated = str_replace($old_pkg, $new_pkg, $content);
                    if ($updated !== $content) {
                        file_put_contents($filePath, $updated);
                    }
                }
            }
        }

        // 5. Update app name occurrences in strings.xml and build.sh name mappings
        $build_sh_path = "$new_dir/build.sh";
        if (file_exists($build_sh_path)) {
            $content = file_get_contents($build_sh_path);
            $content = str_replace("APP_NAME=\"$old_name\"", "APP_NAME=\"$new_name\"", $content);
            file_put_contents($build_sh_path, $content);
        }

        $strings_xml_path = "$new_dir/res/values/strings.xml";
        if (file_exists($strings_xml_path)) {
            $content = file_get_contents($strings_xml_path);
            $content = preg_replace('/<string name="app_name">.*?<\/string>/', '<string name="app_name">' . htmlspecialchars($new_name) . '</string>', $content);
            file_put_contents($strings_xml_path, $content);
        }

        // 6. Run dynamic JIT templates enforcer
        enforce_ssot_templates($updated_proj, $new_dir);

        echo json_encode(['success' => true]);
        break;

    case 'delete_project':
        $id = $_POST['id'] ?? 0;
        $stmt = $db->prepare("SELECT * FROM projects WHERE id = ?");
        $stmt->execute([$id]);
        $proj = $stmt->fetch();
        if ($proj) {
            $proj_dir = get_project_dir($proj['name'], $proj['id']);
            if ($proj_dir) {
                delete_dir($proj_dir);
            }
            $db->prepare("DELETE FROM projects WHERE id = ?")->execute([$id]);
        }
        echo json_encode(['success' => true]);
        break;

    case 'save_project_icon':
        $id = (int)($_POST['id'] ?? 0);
        $icon_base64 = $_POST['icon_base64'] ?? '';
        $icon_svg_source = $_POST['icon_svg_source'] ?? '';
        
        $stmt = $db->prepare("SELECT * FROM projects WHERE id = ?");
        $stmt->execute([$id]);
        $proj = $stmt->fetch();
        if (!$proj) {
            echo json_encode(['success' => false, 'error' => 'Project not found']);
            exit;
        }
        
        $proj_dir = get_project_dir($proj['name'], $proj['id']);
        if (!$proj_dir) {
            echo json_encode(['success' => false, 'error' => 'Project directory missing']);
            exit;
        }
        
        $manifest_path = $proj_dir . '/AndroidManifest.xml';
        if (!file_exists($manifest_path)) {
            echo json_encode(['success' => false, 'error' => 'AndroidManifest.xml not found']);
            exit;
        }
        
        // 1. Determine icon filename from manifest
        $manifest = file_get_contents($manifest_path);
        $icon_name = 'app_icon';
        if (preg_match('/android:icon="@drawable\/([a-zA-Z0-9_]+)"/', $manifest, $matches)) {
            $icon_name = $matches[1];
        } else if (preg_match('/android:icon="@mipmap\/([a-zA-Z0-9_]+)"/', $manifest, $matches)) {
            // Rewrite mipmap to drawable for simple uncompressed single icon asset pipeline
            $manifest = preg_replace('/android:icon="@mipmap\/[a-zA-Z0-9_]+"/', 'android:icon="@drawable/app_icon"', $manifest);
            $icon_name = 'app_icon';
        } else if (strpos($manifest, 'android:icon=') === false) {
            // Surgically inject android:icon attribute if completely missing
            $manifest = preg_replace('/<application/i', '<application android:icon="@drawable/app_icon"', $manifest);
            $icon_name = 'app_icon';
        }
        
        // Save updated manifest
        file_put_contents($manifest_path, $manifest);
        
        // 2. Write binary PNG data to res/drawable/
        $drawable_dir = $proj_dir . '/res/drawable';
        if (!is_dir($drawable_dir)) {
            mkdir($drawable_dir, 0777, true);
        }
        
        $image_bytes = base64_decode($icon_base64);
        if (!$image_bytes || strlen($image_bytes) < 8 || substr($image_bytes, 0, 8) !== "\x89PNG\r\n\x1a\n") {
            echo json_encode(['success' => false, 'error' => 'Invalid or corrupted PNG image data']);
            exit;
        }

        // Clean up all existing app_icon variants (e.g. app_icon.xml, app_icon.png) to prevent AAPT2 duplicate collisions
        foreach (glob($drawable_dir . '/' . $icon_name . '.*') as $old_icon) {
            if (file_exists($old_icon)) {
                unlink($old_icon);
            }
        }

        $icon_path = $drawable_dir . '/' . $icon_name . '.png';
        file_put_contents($icon_path, $image_bytes);

        // 3. Write metadata SVG outside the compiled res/ directory to keep aapt2 clean
        if ($icon_svg_source) {
            file_put_contents($proj_dir . '/project_icon_source.svg', $icon_svg_source);
        }
        
        echo json_encode(['success' => true]);
        break;

    case 'check_project_icon':
        $id = (int)($_GET['id'] ?? $_POST['id'] ?? 0);
        $stmt = $db->prepare("SELECT * FROM projects WHERE id = ?");
        $stmt->execute([$id]);
        $proj = $stmt->fetch();
        if (!$proj) {
            echo json_encode(['success' => false, 'error' => 'Project not found']);
            exit;
        }
        $proj_dir = get_project_dir($proj['name'], $proj['id']);
        $has_icon = false;
        $icon_path = '';
        $icon_url = '';
        $icon_svg_source = '';
        
        if ($proj_dir) {
            $manifest_path = $proj_dir . '/AndroidManifest.xml';
            $icon_name = 'app_icon';
            if (file_exists($manifest_path)) {
                $manifest = file_get_contents($manifest_path);
                if (preg_match('/android:icon="@drawable\/([a-zA-Z0-9_]+)"/', $manifest, $matches)) {
                    $icon_name = $matches[1];
                }
            }
            
            $drawable_dir = $proj_dir . '/res/drawable';
            $icon_files = glob($drawable_dir . '/' . $icon_name . '.*');
            if (!empty($icon_files)) {
                $icon_abs = $icon_files[0];
                $has_icon = true;
                $icon_path = 'res/drawable/' . basename($icon_abs);
                $ext = strtolower(pathinfo($icon_abs, PATHINFO_EXTENSION));
                $mime = ($ext === 'xml' || $ext === 'svg') ? 'image/svg+xml' : 'image/png';
                $icon_data = file_get_contents($icon_abs);
                $icon_url = 'data:' . $mime . ';base64,' . base64_encode($icon_data);
            }

            $svg_path = $proj_dir . '/project_icon_source.svg';
            if (file_exists($svg_path)) {
                $icon_svg_source = file_get_contents($svg_path);
            }
        }
        echo json_encode(['success' => true, 'has_icon' => $has_icon, 'icon_path' => $icon_path, 'icon_url' => $icon_url, 'icon_svg_source' => $icon_svg_source]);
        break;

    case 'delete_project_icon':
        $id = (int)($_POST['id'] ?? 0);
        $stmt = $db->prepare("SELECT * FROM projects WHERE id = ?");
        $stmt->execute([$id]);
        $proj = $stmt->fetch();
        if (!$proj) {
            echo json_encode(['success' => false, 'error' => 'Project not found']);
            exit;
        }
        $proj_dir = get_project_dir($proj['name'], $proj['id']);
        if ($proj_dir) {
            $manifest_path = $proj_dir . '/AndroidManifest.xml';
            $icon_name = 'app_icon';
            if (file_exists($manifest_path)) {
                $manifest = file_get_contents($manifest_path);
                if (preg_match('/android:icon="@drawable\/([a-zA-Z0-9_]+)"/', $manifest, $matches)) {
                    $icon_name = $matches[1];
                }
                $manifest = preg_replace('/android:icon="[^"]+"/', '', $manifest);
                file_put_contents($manifest_path, $manifest);
            }
            
            $drawable_dir = $proj_dir . '/res/drawable';
            if (is_dir($drawable_dir)) {
                foreach (glob($drawable_dir . '/' . $icon_name . '.*') as $old_icon) {
                    if (file_exists($old_icon)) {
                        unlink($old_icon);
                    }
                }
            }

            $svg_path = $proj_dir . '/project_icon_source.svg';
            if (file_exists($svg_path)) {
                unlink($svg_path);
            }
        }
        echo json_encode(['success' => true]);
        break;

    case 'upload_keystore':
$id = (int)($_POST['id'] ?? 0);
$stmt = $db->prepare("SELECT * FROM projects WHERE id = ?");
$stmt->execute([$id]);
$proj = $stmt->fetch();
            
if (!$proj) {
    echo json_encode(['success' => false, 'error' => 'Project not found']);
    exit;
}

$proj_dir = get_project_dir($proj['name'], $proj['id']);
if (!$proj_dir) {
    echo json_encode(['success' => false, 'error' => 'Project folder missing']);
    exit;
}

$mode = trim($_POST['mode'] ?? 'custom');
    
if ($mode === 'debug') {
    // Read existing config parameters to preserve them if we are just switching to debug mode
    $existing_storepass = '';
    $existing_alias = '';
    $existing_keypass = '';
    $conf_path = $proj_dir . '/signing.conf';
    if (file_exists($conf_path)) {
        $conf_lines = file($conf_path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        foreach ($conf_lines as $line) {
            if (strpos($line, 'KS_PASS=') === 0) {
                $existing_storepass = trim(substr($line, 8), " \"'");
            } elseif (strpos($line, 'KEY_ALIAS=') === 0) {
                $existing_alias = trim(substr($line, 10), " \"'");
            } elseif (strpos($line, 'KEY_PASS=') === 0) {
                $existing_keypass = trim(substr($line, 9), " \"'");
            }
        }
    }
        
    $conf_content = "SIGNING_MODE=\"debug\"\n";
    if ($existing_storepass) {
        $conf_content .= "KS_PASS=\"{$existing_storepass}\"\n";
        $conf_content .= "KEY_ALIAS=\"{$existing_alias}\"\n";
        $conf_content .= "KEY_PASS=\"{$existing_keypass}\"\n";
    }
    file_put_contents($proj_dir . '/signing.conf', $conf_content);
    echo json_encode(['success' => true]);
    exit;
}

$generate = (int)($_POST['generate'] ?? 0);
$storepass = trim($_POST['storepass'] ?? '');
$alias = trim($_POST['alias'] ?? '');
$keypass = trim($_POST['keypass'] ?? '');

// Load existing configuration details as safe fallbacks
$existing_storepass = '';
$existing_alias = '';
$existing_keypass = '';
$conf_path = $proj_dir . '/signing.conf';
if (file_exists($conf_path)) {
    $conf_lines = file($conf_path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    foreach ($conf_lines as $line) {
        if (strpos($line, 'KS_PASS=') === 0) {
            $existing_storepass = trim(substr($line, 8), " \"'");
        } elseif (strpos($line, 'KEY_ALIAS=') === 0) {
            $existing_alias = trim(substr($line, 10), " \"'");
        } elseif (strpos($line, 'KEY_PASS=') === 0) {
            $existing_keypass = trim(substr($line, 9), " \"'");
        }
    }
}

// Dynamically preserve unchanged values
if (!$alias) {
    $alias = $existing_alias;
}
if (!$storepass) {
    $storepass = $existing_storepass;
}
if (!$keypass) {
    $keypass = ($storepass === $existing_storepass) ? $existing_keypass : $storepass;
}

if (!$storepass || !$alias) {
    echo json_encode(['success' => false, 'error' => 'Missing password or alias']);
    exit;
}

if (!$keypass) {
    $keypass = $storepass;
}

$dest_keystore = $proj_dir . '/custom.keystore';
if ($generate === 1) {// Generate a brand new production-grade PKCS12 keystore using PHP's native OpenSSL extension.
    // This eliminates any dependency on system 'keytool' binaries on the hosting server!
    if (file_exists($dest_keystore)) {
        unlink($dest_keystore);
    }

    // Create a temporary minimalist openssl.cnf to bypass missing system configuration bugs
    $temp_cnf = $proj_dir . '/temp_openssl.cnf';
    $cnf_content = "[req]\ndistinguished_name = req_distinguished_name\n[req_distinguished_name]\n";
    file_put_contents($temp_cnf, $cnf_content);

    $dn = array(
        "countryName" => "US",
        "stateOrProvinceName" => "California",
        "localityName" => "San Francisco",
        "organizationName" => "ApkStudio",
        "organizationalUnitName" => "ApkStudio Developer",
        "commonName" => "ApkStudio Developer"
    );

    // 1. Generate a robust 2048-bit RSA Private Key natively
    $privkey = openssl_pkey_new(array(
        "private_key_bits" => 2048,
        "private_key_type" => OPENSSL_KEYTYPE_RSA,
        "config" => $temp_cnf
    ));

    if (!$privkey) {
        $err = openssl_error_string() ?: 'Failed to create private key. Check OpenSSL config.';
        if (file_exists($temp_cnf)) unlink($temp_cnf);
        echo json_encode(['success' => false, 'error' => 'Generation failed: ' . $err]);
        exit;
    }

    // 2. Create the Certificate Signing Request (CSR)
    $csr = openssl_csr_new($dn, $privkey, array(
        'digest_alg' => 'sha256',
        'config' => $temp_cnf
    ));
    if (!$csr) {
        $err = openssl_error_string() ?: 'Failed to create CSR.';
        if (file_exists($temp_cnf)) unlink($temp_cnf);
        echo json_encode(['success' => false, 'error' => 'Generation failed: ' . $err]);
        exit;
    }

    // 3. Sign the Certificate (Self-Signed, valid for 10,000 days / ~27 years)
    $sscert = openssl_csr_sign($csr, null, $privkey, 10000, array(
        'digest_alg' => 'sha256',
        'config' => $temp_cnf
    ));
    if (!$sscert) {
        $err = openssl_error_string() ?: 'Failed to sign certificate.';
        if (file_exists($temp_cnf)) unlink($temp_cnf);
        echo json_encode(['success' => false, 'error' => 'Generation failed: ' . $err]);
        exit;
    }

    // 4. Export the private key & certificate to a standard PKCS12 Keystore store
    $pkcs12_content = "";
    $export_success = openssl_pkcs12_export($sscert, $pkcs12_content, $privkey, $storepass, array(
        'friendly_name' => $alias
    ));

    // Clean up the temporary openssl.cnf file immediately
    if (file_exists($temp_cnf)) {
        unlink($temp_cnf);
    }

    if (!$export_success || empty($pkcs12_content)) {
        $err = openssl_error_string() ?: 'Failed to export PKCS12.';
        echo json_encode(['success' => false, 'error' => 'Generation failed: ' . $err]);
        exit;
    }

    // Save the generated PKCS12 keystore bytes natively
    file_put_contents($dest_keystore, $pkcs12_content);
} else {if (!isset($_FILES['keystore_file']) || $_FILES['keystore_file']['error'] !== UPLOAD_ERR_OK) {
            echo json_encode(['success' => false, 'error' => 'Invalid file upload']);
            exit;
        }

        if (!move_uploaded_file($_FILES['keystore_file']['tmp_name'], $dest_keystore)) {
            echo json_encode(['success' => false, 'error' => 'Failed to save keystore file']);
            exit;
        }
    }

    // Output parameters in sourceable key=value shell format
    $conf_content = "SIGNING_MODE=\"custom\"\n";
    $conf_content .= "KS_PASS=\"{$storepass}\"\n";
    $conf_content .= "KEY_ALIAS=\"{$alias}\"\n";
    $conf_content .= "KEY_PASS=\"{$keypass}\"\n";
            
    file_put_contents($proj_dir . '/signing.conf', $conf_content);

    echo json_encode(['success' => true]);
    break;case 'check_keystore':
$id = (int)($_GET['id'] ?? $_POST['id'] ?? 0);
$stmt = $db->prepare("SELECT * FROM projects WHERE id = ?");
$stmt->execute([$id]);
$proj = $stmt->fetch();
if (!$proj) {
    echo json_encode(['success' => false, 'error' => 'Project not found']);
    exit;
}
$proj_dir = get_project_dir($proj['name'], $proj['id']);
$has_key = $proj_dir && file_exists($proj_dir . '/custom.keystore');
$has_conf = $proj_dir && file_exists($proj_dir . '/signing.conf');
        
$alias = '';
$storepass = '';
$keypass = '';
$signing_mode = 'debug';

if (file_exists($proj_dir . '/signing.conf')) {
    $conf_lines = file($proj_dir . '/signing.conf', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    foreach ($conf_lines as $line) {
        if (strpos($line, 'SIGNING_MODE=') === 0) {
            $signing_mode = trim(substr($line, 13), " \"'");
        } elseif (strpos($line, 'KEY_ALIAS=') === 0) {
            $alias = trim(substr($line, 10), " \"'");
        } elseif (strpos($line, 'KS_PASS=') === 0) {
            $storepass = trim(substr($line, 8), " \"'");
        } elseif (strpos($line, 'KEY_PASS=') === 0) {
            $keypass = trim(substr($line, 9), " \"'");
        }
    }
}

// Default to custom if key and config exist but SIGNING_MODE parameter was never declared (Legacy Fallback)
if ($has_key && $signing_mode === 'debug' && !preg_match('/SIGNING_MODE=/', file_get_contents($proj_dir . '/signing.conf') ?: '')) {
    $signing_mode = 'custom';
}
        
echo json_encode([
    'success' => true, 
    'has_key' => $has_key,
    'has_conf' => $has_conf,
    'mode' => $signing_mode,
    'alias' => $alias,
    'storepass' => $storepass,
    'keypass' => $keypass
]);
break;

    case 'delete_keystore':
        $id = (int)($_POST['id'] ?? 0);
        $stmt = $db->prepare("SELECT * FROM projects WHERE id = ?");
        $stmt->execute([$id]);
        $proj = $stmt->fetch();
        if (!$proj) {
            echo json_encode(['success' => false, 'error' => 'Project not found']);
            exit;
        }
        $proj_dir = get_project_dir($proj['name'], $proj['id']);
        if ($proj_dir) {
            if (file_exists($proj_dir . '/custom.keystore')) {
                unlink($proj_dir . '/custom.keystore');
            }
            if (file_exists($proj_dir . '/signing.conf')) {
                unlink($proj_dir . '/signing.conf');
            }
        }
        echo json_encode(['success' => true]);
        break;

    case 'download_zip':
        sync_projects_from_filesystem($db);
        $id_param = $_GET['id'] ?? $_POST['id'] ?? $_GET['name'] ?? $_POST['name'] ?? 0;
        
        $proj = null;
        if (is_numeric($id_param) && (int)$id_param > 0) {
            $stmt = $db->prepare("SELECT * FROM projects WHERE id = ?");
            $stmt->execute([(int)$id_param]);
            $proj = $stmt->fetch();
        }
        
        if (!$proj && !empty($id_param)) {
            $stmt = $db->prepare("SELECT * FROM projects WHERE name = ? OR package_name = ?");
            $stmt->execute([trim($id_param), trim($id_param)]);
            $proj = $stmt->fetch();
        }

        if (!$proj) {
            http_response_code(404);
            die("Error: Project '{$id_param}' not found.\nPlease open the ApkStudio UI, select your project, and click 'Compile in Termux' to get the current project URL.");
        }

        $proj_dir = get_project_dir($proj['name'], $proj['id']);
        if (!$proj_dir) {
            http_response_code(404);
            die("Error: Project folder for '{$proj['name']}' not found on disk.");
        }
        
        enforce_ssot_templates($proj, $proj_dir);
        
        // JIT compile build.sh with the live network request URL so Termux can auto-sync
        $tpl_dir = __DIR__ . "/../templates";
        $protocol = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https')) ? "https" : "http";
        $download_url = $protocol . "://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
        
        $zip_file = sys_get_temp_dir() . "/apkstudio_{$id}_" . time() . ".zip";
        $zip = new ZipArchive();
        if ($zip->open($zip_file, ZipArchive::CREATE | ZipArchive::OVERWRITE) === true) {
            $files = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($proj_dir), RecursiveIteratorIterator::LEAVES_ONLY);
            foreach ($files as $name => $file) {
                if (!$file->isDir()) {
                    $file_path = $file->getRealPath();
                    $rel_path = substr($file_path, strlen($proj_dir) + 1);
                    $rel_path = str_replace('\\', '/', $rel_path);
                    
                    if ($rel_path === 'build.sh') {
                        $base_script = file_get_contents($file_path);
                        
                        // Replace DOWNLOAD_URL if it exists in the base script (e.g. if standard user included it)
                        if (strpos($base_script, 'DOWNLOAD_URL="') !== false) {
                            $base_script = preg_replace('/DOWNLOAD_URL="[^"]*"/', 'DOWNLOAD_URL="' . $download_url . '"', $base_script);
                        }

                        // SSOT Guarantee: Dynamically inject build log export trap if missing from custom project build scripts
                        if (strpos($base_script, 'export_build_log') === false) {
                            $appNameEsc = addslashes($proj['name']);
                            $log_trap_code = "\nAPP_NAME=\"{$appNameEsc}\"\n"
                                . "LOG_FILE=\"\$(pwd)/build.log\"\n"
                                . "exec > >(tee -a \"\$LOG_FILE\") 2>&1\n\n"
                                . "export_build_log() {\n"
                                . "    trap - EXIT ERR\n"
                                . "    sync 2>/dev/null || true\n"
                                . "    local legacy_dir=\"/sdcard/Download/ApkStudio_Logs\"\n"
                                . "    local target_dir=\"/sdcard/Conjure_Config/ApkStudio_Logs\"\n"
                                . "    if [ -d \"\$legacy_dir\" ]; then\n"
                                . "        mkdir -p \"\$target_dir\" 2>/dev/null || true\n"
                                . "        mv \"\$legacy_dir\"/* \"\$target_dir\"/ 2>/dev/null || true\n"
                                . "        rmdir \"\$legacy_dir\" 2>/dev/null || true\n"
                                . "    fi\n"
                                . "    mkdir -p \"\$target_dir\" 2>/dev/null || true\n"
                                . "    local saved_log=\"\$target_dir/\${APP_NAME}-build.log\"\n"
                                . "    local latest_log=\"\$target_dir/latest-build.log\"\n"
                                . "    if [ -f \"\$LOG_FILE\" ]; then\n"
                                . "        cp \"\$LOG_FILE\" \"\$saved_log\" 2>/dev/null || true\n"
                                . "        cp \"\$LOG_FILE\" \"\$latest_log\" 2>/dev/null || true\n"
                                . "        if command -v termux-clipboard-set &>/dev/null; then\n"
                                . "            (echo '```text'; cat \"\$LOG_FILE\" | sed -r \"s/\\x1B\\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g\" | tr -d '\\r'; echo \"\"; echo '```') | termux-clipboard-set 2>/dev/null || true\n"
                                . "        fi\n"
                                . "    fi\n"
                                . "}\n"
                                . "trap 'export_build_log' EXIT\n\n";

                            if (preg_match('/^#!.*\n/', $base_script, $m)) {
                                $base_script = $m[0] . $log_trap_code . substr($base_script, strlen($m[0]));
                            } else {
                                $base_script = $log_trap_code . $base_script;
                            }
                        }
                        
                        // Load, hydrate and append the build appendix
                        $replacements = [
                            '{{APP_NAME}}' => $proj['name'], 
                            '{{PACKAGE_NAME}}' => $proj['package_name'],
                            '{{WRAPPER_URL}}' => $proj['wrapper_url'] ?? '',
                            '{{DOWNLOAD_URL}}' => $download_url
                        ];
                        $appendix = strtr(file_get_contents("$tpl_dir/build_appendix.tpl"), $replacements);
                        
                        $full_script = $base_script . "\n\n" . $appendix;
                        $zip->addFromString($rel_path, $full_script);
                    } else {
                        $zip->addFile($file_path, $rel_path);
                    }
                }
            }
            $zip->close();
            
            header('Content-Type: application/zip', true);
            header('Content-Disposition: attachment; filename="' . basename($proj_dir) . '.zip"');
            header('Content-Length: ' . filesize($zip_file));
            readfile($zip_file);
            unlink($zip_file);
            exit;
        }
        die("Failed to create zip");

    case 'get_file_tree':
        $id = (int)($_POST['id'] ?? 0);
        $stmt = $db->prepare("SELECT * FROM projects WHERE id = ?");
        $stmt->execute([$id]);
        $proj = $stmt->fetch();
        
        if (!$proj) {
            echo json_encode(['success' => false, 'error' => 'Project not found']);
            exit;
        }

        $proj_dir = get_project_dir($proj['name'], $proj['id']);
        if (!$proj_dir) {
            echo json_encode(['success' => false, 'error' => 'Project folder missing']);
            exit;
        }
        
        enforce_ssot_templates($proj, $proj_dir);

        if (!function_exists('build_tree')) {
            function build_tree($dir, $base_dir) {
                $result = [];
                $files = array_diff(scandir($dir), ['.', '..']);
                foreach ($files as $file) {
                    $path = "$dir/$file";
                    $rel_path = str_replace($base_dir . '/', '', $path);
                    $is_dir = is_dir($path);
                    $result[] = [
                        'name' => $file,
                        'path' => $rel_path,
                        'is_dir' => $is_dir,
                        'children' => $is_dir ? build_tree($path, $base_dir) : []
                    ];
                }
                usort($result, function($a, $b) {
                    if ($a['is_dir'] == $b['is_dir']) return strcasecmp($a['name'], $b['name']);
                    return $a['is_dir'] ? -1 : 1;
                });
                return $result;
            }
        }

        $tree = build_tree($proj_dir, $proj_dir);
        $full_base = "apps/ApkStudio/data/projects/" . basename($proj_dir);
        echo json_encode(['success' => true, 'tree' => $tree, 'base_path' => $full_base]);
        break;

    case 'get_file_content':
        $id = (int)($_POST['id'] ?? 0);
        $rel_path = $_POST['path'] ?? '';
        
        if (strpos($rel_path, '..') !== false) {
            echo json_encode(['success' => false, 'error' => 'Invalid path']);
            exit;
        }

        $stmt = $db->prepare("SELECT * FROM projects WHERE id = ?");
        $stmt->execute([$id]);
        $proj = $stmt->fetch();
        
        if ($proj) {
            $proj_dir = get_project_dir($proj['name'], $proj['id']);
            if ($proj_dir) {
                enforce_ssot_templates($proj, $proj_dir);
                $file_path = $proj_dir . '/' . $rel_path;
                if (file_exists($file_path) && !is_dir($file_path)) {
                    $content = file_get_contents($file_path);
                    echo json_encode(['success' => true, 'content' => $content]);
                    exit;
                }
            }
        }
        echo json_encode(['success' => false, 'error' => 'File not found']);
        break;

    default:
        echo json_encode(['success' => false, 'error' => 'Unknown action']);
        break;
}
exit;