<?xml version="1.0" encoding="utf-8"?>
<!--
============================================================================
⚠️ WARNING: DO NOT EDIT THIS FILE DIRECTLY!
This is a dynamically synchronized child template.
All modifications must be made strictly to the master template at:
apps/ApkStudio/templates/strings.xml.tpl
============================================================================
-->

<resources>
    <string name="app_name">{{APP_NAME}}</string>
</resources>